name: choir_app_anggota
description: PCU Choir Member App — Aplikasi anggota paduan suara PCU
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  http: ^1.2.1
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  mobile_scanner: ^4.0.1
  url_launcher: ^6.3.0
  intl: ^0.20.0
  lucide_icons: ^0.257.0
  flutter_local_notifications: ^22.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
